// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriRed.Data;

#nullable disable

namespace NutriRed.Data.Migrations
{
    [DbContext(typeof(NutriRedDbContext))]
    partial class NutriRedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriRed.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Donacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoComprobante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("DonanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VoluntarioReceptorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoComprobante")
                        .IsUnique();

                    b.HasIndex("DonanteId");

                    b.ToTable("Donaciones");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.DonacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonacionId")
                        .HasColumnType("int");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonacionId");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DonacionDetalles");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Donante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Donantes");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concretada")
                        .HasColumnType("bit");

                    b.Property<string>("DniReceptor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHoraEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaDigital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoNoEntrega")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreReceptor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PaqueteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoReceptor")
                        .HasColumnType("int");

                    b.Property<string>("VinculoConTitular")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VoluntarioDespachoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PaqueteId")
                        .IsUnique();

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.FamiliaBeneficiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoTitular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CantidadIntegrantes")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DniTitular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreTitular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("FamiliasBeneficiarias");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.Property<int>("Motivo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoSeguimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("FamiliaBeneficiariaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoPaqueteId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioArmadorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSeguimiento")
                        .IsUnique();

                    b.HasIndex("FamiliaBeneficiariaId");

                    b.HasIndex("TipoPaqueteId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.PaqueteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EsSustituto")
                        .HasColumnType("bit");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.Property<int>("PaqueteId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoSustituidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProductoSustituidoId");

                    b.ToTable("PaqueteDetalles");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.PlantillaPaqueteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadRequerida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPaqueteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TipoPaqueteId");

                    b.ToTable("PlantillaPaqueteDetalles");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.TipoPaquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MaxIntegrantes")
                        .HasColumnType("int");

                    b.Property<int>("MinIntegrantes")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposPaquete");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Donacion", b =>
                {
                    b.HasOne("NutriRed.Domain.Entities.Donante", "Donante")
                        .WithMany("Donaciones")
                        .HasForeignKey("DonanteId");

                    b.Navigation("Donante");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.DonacionDetalle", b =>
                {
                    b.HasOne("NutriRed.Domain.Entities.Donacion", "Donacion")
                        .WithMany("Detalles")
                        .HasForeignKey("DonacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriRed.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriRed.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donacion");

                    b.Navigation("Lote");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Entrega", b =>
                {
                    b.HasOne("NutriRed.Domain.Entities.Paquete", "Paquete")
                        .WithOne("Entrega")
                        .HasForeignKey("NutriRed.Domain.Entities.Entrega", "PaqueteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Lote", b =>
                {
                    b.HasOne("NutriRed.Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.MovimientoStock", b =>
                {
                    b.HasOne("NutriRed.Domain.Entities.Lote", "Lote")
                        .WithMany("Movimientos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Paquete", b =>
                {
                    b.HasOne("NutriRed.Domain.Entities.FamiliaBeneficiaria", "FamiliaBeneficiaria")
                        .WithMany("HistorialPaquetes")
                        .HasForeignKey("FamiliaBeneficiariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriRed.Domain.Entities.TipoPaquete", "TipoPaquete")
                        .WithMany()
                        .HasForeignKey("TipoPaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamiliaBeneficiaria");

                    b.Navigation("TipoPaquete");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.PaqueteDetalle", b =>
                {
                    b.HasOne("NutriRed.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriRed.Domain.Entities.Paquete", "Paquete")
                        .WithMany("Detalles")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriRed.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriRed.Domain.Entities.Producto", "ProductoSustituido")
                        .WithMany()
                        .HasForeignKey("ProductoSustituidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lote");

                    b.Navigation("Paquete");

                    b.Navigation("Producto");

                    b.Navigation("ProductoSustituido");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.PlantillaPaqueteDetalle", b =>
                {
                    b.HasOne("NutriRed.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriRed.Domain.Entities.TipoPaquete", "TipoPaquete")
                        .WithMany("ItemsPlantilla")
                        .HasForeignKey("TipoPaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("TipoPaquete");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Producto", b =>
                {
                    b.HasOne("NutriRed.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Donacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Donante", b =>
                {
                    b.Navigation("Donaciones");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.FamiliaBeneficiaria", b =>
                {
                    b.Navigation("HistorialPaquetes");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Lote", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Paquete", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("NutriRed.Domain.Entities.TipoPaquete", b =>
                {
                    b.Navigation("ItemsPlantilla");
                });
#pragma warning restore 612, 618
        }
    }
}
